### ISSUE TITLE
`logsExporter` does not work

### ISSUE THREAD

**Issue by debajyoti-truefoundry** [siglens/charts#18]
Error log:
```
unexpected error error_class=Elasticsearch::UnsupportedProductError error="The client noticed that the server is not Elasticsearch and we do not support this unknown product."
```

Chart detail:
```yaml
repo_url: https://siglens.github.io/charts
chart: siglens
version: 0.1.3
```

Siglens image: siglens/siglens:1.0.7
Log exporter image: fluent/fluentd-kubernetes-daemonset:v1.14-debian-elasticsearch7-1
